TOOLS = [
    {
        "name": "web_search",
        "path": "anet.AnetTools.web_search",
        "description": "Searches the web for current information using the Exa API.",
        "enabled": True,
    },
    {
        "name": "open_app",
        "path": "anet.AnetTools.open_app",
        "description": "Full Windows desktop control: open apps, find/focus windows, type text, click UI elements, send keyboard shortcuts, take screenshots, and read screen text.",
        "enabled": True,
    },
    {
        "name": "checker",
        "path": "anet.AnetTools.checker.index",
        "description": "Validates task results: classifies success/failure/partial and diagnoses failures with retry suggestions.",
        "enabled": True,
    },
    {
        "name": "compare-screenshot",
        "path": "anet.AnetTools.compare_screenshot.index",
        "description": "Takes screenshots and uses a vision model to verify whether a desktop automation task produced the expected visual change.",
        "enabled": False,
    },
    {
        "name": "download_file",
        "path": "anet.AnetTools.download_file",
        "description": "Download a file from a URL to local disk. Returns local path and image dimensions for quality checking.",
        "enabled": True,
    },
    {
        "name": "web_fetch",
        "path": "anet.AnetTools.web_fetch",
        "description": "Fetch a URL and read its content as clean markdown. Use after web_search to read a result, or for any doc/article/API-reference URL. For binaries use download_file.",
        "enabled": True,
    },
    {
        "name": "file_tool",
        "path": "anet.AnetTools.file_tool",
        "description": "OS-level file operations: read/write files, create folders, copy/move/delete/rename, list directories, search, parse CSV/JSON, read line ranges, zip/unzip.",
        "enabled": True,
    },
{
        "name": "shell_tool",
        "path": "anet.AnetTools.shell_tool",
        "description": "Run shell commands with a timeout. Use for tests (pytest, npm test), linters (ruff, eslint), and build scripts.",
        "enabled": True,
    },
    {
        "name": "edit_tool",
        "path": "anet.AnetTools.edit_tool",
        "description": "Targeted file editing: replace old_string with new_string. Safer than rewriting whole files. Includes staleness guard and quote normalization.",
        "enabled": True,
    },
    {
        "name": "grep_tool",
        "path": "anet.AnetTools.grep_tool",
        "description": "Search file contents by regex. Uses ripgrep when available, Python fallback otherwise. Supports content/files/count output modes and context lines.",
        "enabled": True,
    },
    {
        "name": "glob_tool",
        "path": "anet.AnetTools.glob_tool",
        "description": "Find files matching a glob pattern, sorted by modification time. Use to locate files before reading or editing.",
        "enabled": True,
    },
    {
        "name": "todo_tool",
        "path": "anet.AnetTools.todo_tool",
        "description": "Session-scoped task checklist. Write a plan at task start, mark items in_progress/completed as you work. Visible in the live spinner.",
        "enabled": True,
    },
    {
        "name": "process_tool",
        "path": "anet.AnetTools.process_tool",
        "description": "Start a command, capture output until a success/failure pattern matches or timeout expires. Use to verify dev servers and build tools actually work.",
        "enabled": True,
    },
    {
        "name": "diagnose_tool",
        "path": "anet.AnetTools.diagnose_tool",
        "description": "Run linters and type-checkers on a file or directory. Auto-detects language: ruff+pyright for Python, eslint+tsc for JS/TS. Returns structured per-line diagnostics with PASS/FAIL summary.",
        "enabled": True,
    },
    {
        "name": "memory_tool",
        "path": "anet.AnetTools.memory_tool",
        "description": "Persistent cross-session memory. Save facts (project paths, decisions, preferences), search by keyword, list all entries, delete stale ones. Memories survive across restarts.",
        "enabled": True,
    },
    {
        "name": "conflict_tool",
        "path": "anet.AnetTools.conflict_tool",
        "description": "Resolve git merge conflicts. List conflicts in a file or directory, inspect each one (ours/theirs/base), and resolve with @ours, @theirs, @base, or custom text.",
        "enabled": True,
    },
    {
        "name": "lsp_tool",
        "path": "anet.AnetTools.lsp_tool",
        "description": "IDE-level code intelligence via Language Server Protocol. diagnostics (real errors/warnings), hover (type info), definition (go-to-def), references (find usages), rename (workspace-wide), symbols (list file symbols). Supports Python/Go/TypeScript/JavaScript/C/C++/Rust.",
        "enabled": True,
    },
    {
        "name": "spawn_tool",
        "path": "anet.AnetTools.spawn_tool",
        "description": "Spawn a specialist sub-agent mid-task to delegate work and return its result. Auto-injected into every agent — no per-agent config needed.",
        "enabled": True,
    },
    {
        "name": "ask_user",
        "path": "anet.AnetTools.ask_user",
        "description": "Ask the user a clarifying question and wait for their answer. Use only when the task is genuinely ambiguous and guessing wrong would waste work.",
        "enabled": True,
    },
    {
        "name": "code_execution",
        "path": "anet.AnetTools.code_execution",
        "description": "Run a Python snippet and return its output (stdout + auto-printed trailing expression). Use for computation, data transforms, parsing, and verification.",
        "enabled": True,
    },
    {
        "name": "registrar",
        "path": "anet.AnetTools.registrar",
        "description": "Smith-only: register ExTools/ExAgents and attach tools/MCP servers to agents by safely editing exanet.config.yaml. Never touches the core anet/ package or anet.config.yaml.",
        "enabled": True,
    },
    {
        "name": "pack_tool",
        "path": "anet.AnetTools.pack_tool",
        "description": "PackSmith-only: inspect/export/import shareable ANet packs. Export strips all secrets (.env) and heavy junk; import extracts into shared_packs/. Never runs pack code.",
        "enabled": True,
    },
]
